project_id = "nracebwmywbyuywhucwo"

[functions.api-generate]
verify_jwt = false

[functions.api-templates]
verify_jwt = false

[functions.api-usage]
verify_jwt = false

[functions.render]
verify_jwt = false

[functions.svg-to-png-renderer]
verify_jwt = false

[functions.test-render]
verify_jwt = false